version: 2.1

jobs:
  documentation:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt -r requirements-dev.txt

      - run:
          name: Build documentation
          command: cd docs && make html

      - store_artifacts:
          path: ./docs/build/html

workflows:
  main:
    jobs:
      - documentation:
